Annotate '@Lob' entity fields as TextType to aid Hibernate/PostgreSQL driver
The PostgreSQL hibernate driver is failing to load values for fields marked @Lob.
The annotation was introduced when the fields were migrated from varchar to text.
PostgreSQL expect a value reference in this column (a integer-type pointer to the actual column value stored externally), and it fails when inline text is found instead.

The resulting error is:
```
  org.postgresql.util.PSQLException: Bad value for type long : <application description>
```

See also: https://github.com/Netflix/genie/issues/636